name: DevOps Pipeline

on:
  workflow_dispatch:
   inputs:
      stage:
        description: 'Deployment stage'
        required: true
        default: 'TEST'

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to Repo
        uses: actions/checkout@main

      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:ci
        
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@main
        
      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Substitute variables in JSON files
        uses: ngduc/replace-action@v1
        with:
          path: 'src/environments/environment.ts' # Path to your environment file
          pattern: 'apiUrl: .*' # Pattern to match the variable to replace
          replacement: 'apiUrl: "sub sub sub"' # Replacement value

      - name: Run Build
        run: npm run build

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@main
        with:
          name: public
          path: ./public
          
  deploy:
      name: Deploy to Firebase
      runs-on: ubuntu-latest
      # only run if build job complte successfully
      needs: [build]
      steps:
        # building the app before deploy
        - name: Checkout to Repo
          uses: actions/checkout@main
  
        - name: Setup Node
          uses: actions/setup-node@main
          with:
            node-version: "20.x"
  
        # Install the dependencies need to build the app
        - name: Install Dependencies
          run: npm install
        # build the app
        - name: Build the app artifact for prod
          run: npm run build 
  
        # ddeploy the app artifact to firebase
        - name: Deploy angular app to Firebase
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            GCP_SA_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
